Repository okstring/todo-list, pull requests merged in 2021-04, with the labels that each got.

#8 [BE] DB setting
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/team06/todo/TodoApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/team06/todo/TodoApplicationTests.java
Labels: good first issue

#11 [BE] Card CRUD 구현
  backend/src/main/java/com/team06/todo/controller/CardsController.java
  backend/src/main/java/com/team06/todo/domain/Card.java
  backend/src/main/java/com/team06/todo/repository/CardRepository.java
  backend/src/main/java/com/team06/todo/service/CardsService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: enhancement

#16 [BE] Action API 구현
  backend/src/main/java/com/team06/todo/controller/ActionsController.java
  backend/src/main/java/com/team06/todo/controller/CardsController.java
  backend/src/main/java/com/team06/todo/domain/Action.java
  backend/src/main/java/com/team06/todo/domain/ActionType.java
  backend/src/main/java/com/team06/todo/domain/Card.java
  backend/src/main/java/com/team06/todo/domain/ColumnType.java
  backend/src/main/java/com/team06/todo/dto/ActionsResponseDto.java
  backend/src/main/java/com/team06/todo/repository/ActionsRepository.java
  backend/src/main/java/com/team06/todo/repository/CardsRepository.java
  backend/src/main/java/com/team06/todo/service/ActionsService.java
  backend/src/main/java/com/team06/todo/service/CardsService.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: BE

#23 [BE] 1차 코드리뷰 반영하여 수정
  backend/src/main/java/com/team06/todo/TodoApplication.java
  backend/src/main/java/com/team06/todo/controller/ActionsController.java
  backend/src/main/java/com/team06/todo/controller/CardsController.java
  backend/src/main/java/com/team06/todo/domain/Action.java
  backend/src/main/java/com/team06/todo/domain/Card.java
  backend/src/main/java/com/team06/todo/domain/ColumnType.java
  backend/src/main/java/com/team06/todo/dto/ActionResponseDto.java
  backend/src/main/java/com/team06/todo/dto/ActionsResponse.java
  backend/src/main/java/com/team06/todo/dto/ActionsResponseDto.java
  backend/src/main/java/com/team06/todo/dto/CardCreateRequestDto.java
  backend/src/main/java/com/team06/todo/dto/CardMoveRequestDto.java
  backend/src/main/java/com/team06/todo/dto/CardResponseDto.java
  backend/src/main/java/com/team06/todo/dto/CardUpdateRequestDto.java
  backend/src/main/java/com/team06/todo/dto/CardsResponse.java
  backend/src/main/java/com/team06/todo/service/ActionsService.java
  backend/src/main/java/com/team06/todo/service/CardsService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: BE, enhancement

#28 [BE] ubuntu 18.04, mysql 5.7 사용하여 재배포
  backend/gradlew
  backend/src/main/resources/application.properties
  backend/src/test/java/com/team06/todo/TodoApplicationTests.java
Labels: BE, bug

#30 [BE] fix : 생성 시간 소수점 이하 생략
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/todo-list.iml
  .idea/vcs.xml
  backend/src/main/java/com/team06/todo/domain/Card.java
  backend/src/main/java/com/team06/todo/dto/CardResponseDto.java
  backend/src/main/resources/application.properties
Labels: BE, bug
